# Generated by Django 3.2.7 on 2021-09-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_title_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
