# Generated by Django 3.2.7 on 2021-09-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_video_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
