# Generated by Django 3.2.7 on 2021-09-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20210930_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timestamp',
        ),
    ]
