# Generated by Django 3.2.7 on 2021-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_remove_video_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
