# Generated by Django 3.2.7 on 2021-09-30 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 30, 9, 4, 6, 453525, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
